---
- name: Disable swap temporarily
  command: swapoff -a
  become: yes
- name: Ensure swap is disabled permanently
  lineinfile:
        path: /etc/fstab
        regexp: '^/swapfile'
        state: absent
  become: yes

- name: Initialize Kubernetes cluster
  ansible.builtin.command: "sudo kubeadm init --pod-network-cidr={{ pod_network_cidr }} --apiserver-advertise-address={{ master_ip }}"
  register: kubeadm_init
  
- name: Create .kube directory
  file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    mode: '0755'
  become_user: "{{ ansible_user }}"

- name: Copy admin.conf to user's kube config
  ansible.builtin.copy:
    src: "/etc/kubernetes/admin.conf"
    dest: "/home/{{ ansible_user }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Install Calico network plugin
  ansible.builtin.command: "kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/calico.yaml"
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"

- name: Generate join command
  ansible.builtin.command: "kubeadm token create --print-join-command"
  register: join_command
  run_once: true

- name: Set join command fact
  set_fact:
    join_command: "{{ join_command.stdout }}"
  run_once: true
