---
- name: Ensure kubelet service is enabled and started
  ansible.builtin.systemd:
    name: kubelet
    enabled: yes
    state: started
  become: yes
- name: Get join command from master
  set_fact:
    join_command: "{{ hostvars[groups['master'][0]]['join_command'] }}"

- name: Join the Kubernetes cluster
  ansible.builtin.command: "{{ join_command }}"