--- 
- name: Configure containerd on all distribution
  template:
    src: containerd-config.toml.j2
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: Restart containerd
