---
- name: Remove Docker and containerd related packages
  apt:
    name: "{{ item }}"
    state: absent
  loop:
    - docker.io
    - docker-doc
    - docker-compose
    - podman-docker
    - containerd
    - runc
  become: yes

- name: Update apt package index
  apt:
    update_cache: yes
  become: yes

- name: Install required packages
  apt:
    name: 
      - ca-certificates
      - curl
    state: present
  become: yes

- name: Create directory for apt keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: yes

- name: Download Docker's official GPG key
  ansible.builtin.get_url:
    url: {{ url_Debia }}
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  become: yes

- name: Add Docker repository
  template:
    src: docker.list.j2
    dest: /etc/apt/sources.list.d/docker.list
    mode: '0644'
  become: yes

- name: Update apt package index with -y
  ansible.builtin.command: apt-get update -y
  become: yes

- name: Install containerd and related packages
  apt:
        name:
          - containerd.io
          - docker-ce-cli
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
  notify: Enable and start containerd on Debian


    