---
- name: Set up Kubernetes Cluster
  hosts: all
  become: yes
  vars_files:
    - vars/main.yaml
  roles:
    - install_containerd
    - install_kubernetes

#- name: Initialize Kubernetes Cluster
      #  hosts: master
      #  become: yes
      #  roles:
      #    - initialize_cluster

- name: Join Worker Nodes to the Kubernetes Cluster
  hosts: all
  become: yes
  roles:
    - initialize_cluster

