---
- name: Add Docker repository for containerd
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable'
    state: present
    update_cache: yes
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Install containerd
  apt:
    name: containerd.io
    state: latest
  ignore_errors: yes
  when: ansible_distribution in ["Ubuntu", "Debian"]


- name: Add Docker repository for containerd
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable'
    state: present
    update_cache: yes

- name: Install containerd
  apt:
    name: containerd.io
    state: latest
  ignore_errors: yes

- name: Add Kubernetes GPG key on Debian-based systems
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg
    state: present

- name: Add Kubernetes repository on Ubuntu
  apt_repository:
    repo: >
      deb [arch=amd64 signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg]
      https://apt.kubernetes.io/ kubernetes-{{ ansible_distribution_release | lower }} main
    state: present
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release in ['bionic', 'focal', 'xenial']

- name: Add Kubernetes repository manually for unsupported Ubuntu releases
  command: >
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg]
    https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release == "jammy"

- name: Update apt cache on Debian-based systems
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: Install Kubernetes dependencies on Ubuntu
  apt:
    name:
      - kubelet=1.27.2
      - kubeadm=1.27.2
      - kubectl=1.27.2
    state: present
  when: ansible_distribution == "Ubuntu"
