---
- name: Gather OS specific information
  setup:

- name: Install necessary packages based on distribution
  block:
    - name: Install prerequisites on Ubuntu
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install prerequisites on CentOS
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present
      when: ansible_distribution == "CentOS"

    - name: Install prerequisites on Debian
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present
      when: ansible_distribution == "Debian"

    - name: Install prerequisites on Fedora
      dnf:
        name:
          - dnf-plugins-core
        state: present
      when: ansible_distribution == "Fedora"

- name: Include tasks based on OS family
  block:
    - name: Include tasks for Debian-based systems
      include_tasks: debian.yaml
      when: ansible_facts['os_family'] == 'Debian'

    - name: Include tasks for RedHat-based systems
      include_tasks: redhat.yaml
      when: ansible_facts['os_family'] == 'RedHat'

- name: Install containerd
  block:
    - name: Install containerd on Ubuntu
      apt:
        name: containerd.io
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install containerd on CentOS
      yum:
        name: containerd.io
        state: present
      when: ansible_distribution == "CentOS"

    - name: Install containerd on Debian
      apt:
        name: containerd.io
        state: present
      when: ansible_distribution == "Debian"

    - name: Install containerd on Fedora
      dnf:
        name: containerd.io
        state: present
      when: ansible_distribution == "Fedora"

- name: Configure and restart containerd
  block:
    - name: Configure containerd
      command: containerd config default | tee /etc/containerd/config.toml

    - name: Restart containerd
      service:
        name: containerd
        state: restarted
        enabled: yes

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Update sysctl settings for Kubernetes
  template:
    src: ../templates/sysctl.conf.j2
    dest: /etc/sysctl.d/k8s.conf
  notify:
    - reload sysctl

- name: Enable and start kubelet
  service:
    name: kubelet
    state: started
    enabled: yes

- name: reload sysctl 
  sysctl:
    reload: yes

