---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes

- name: reload systemd
  ansible.builtin.systemd:
    name: containerd.service
    state: started
    enabled: yes
  become: yes

