---
base_url_Centos: "https://download.docker.com/linux/centos/docker-ce.repo"
gpgkey_Centos: "https://download.docker.com/linux/centos/gpg"
url_Debian: "https://download.docker.com/linux/debian/gpg"
url_Ubuntu: "https://download.docker.com/linux/ubuntu/gpg"
url_Fedora: "https://download.docker.com/linux/fedora/docker-ce.repo"
docker_gpg_key_RedHat_url: "https://download.docker.com/linux/rhel/gpg"
docker_repo_redhat: "https://download.docker.com/linux/rhel/docker-ce.repo"