---
- name: Ensure necessary modules are loaded
  block:
    - name: Create configuration file for kernel modules
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter
      become: yes

    - name: Load necessary modules
      command: modprobe {{ item }}
      with_items:
        - overlay
        - br_netfilter
      become: yes

- name: Configure sysctl parameters for Kubernetes
  block:
    - name: Create sysctl configuration file
      template:
        src: sysctl.conf.j2
        dest: /etc/sysctl.d/k8s.conf
      become: yes

    - name: Apply sysctl parameters
      command: sysctl --system
      become: yes

- name: Install containerd and runc
  apt:
    name:
      - containerd
      - runc
    state: present
  become: yes

- name: Configure containerd
  block:
    - name: Create containerd configuration directory
      file:
        path: /etc/containerd
        state: directory
      become: yes

    - name: Generate default containerd configuration
      command: containerd config default > /etc/containerd/config.toml
      become: yes

    - name: Configure containerd to use systemd cgroup driver
      copy:
        dest: /etc/containerd/config.toml
        content: |
          [plugins."io.containerd.grpc.v1.cri"]
            # Configuration for the containerd CRI plugin
            [plugins."io.containerd.grpc.v1.cri".containerd]
              # Define the snapshotter
              snapshotter = "overlayfs"
              # Default runtime
              default_runtime_name = "runc"
              # Runtimes configuration
              [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
                [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
                  runtime_type = "io.containerd.runc.v1"
                  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
                    SystemdCgroup = true

            # Configuring the pause image used by Kubernetes
            [plugins."io.containerd.grpc.v1.cri".sandbox_image]
              # Ensure that this is set to the recommended pause image version
              image = "registry.k8s.io/pause:3.9"
      become: yes
      notify: Restart containerd

- name: Enable and start containerd service
  systemd:
    name: containerd
    state: started
    enabled: yes
  become: yes

- name: Disable swap
  command: swapoff -a
  become: yes

- name: Remove swap entry from /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '.*swap.*'
    replace: '#\0'
  become: yes

- name: Restart containerd
  systemd:
    name: containerd
    state: restarted
  become: yes

