---
- name: Choose and Install Container Runtime
  hosts: all
  become: yes
  vars_prompt:
    - name: container_runtime
      prompt: "Which container runtime do you want to install? (containerd/cri-o)"
      private: no
      default: containerd

  tasks:
    - name: Ensure valid container_runtime value
      assert:
        that:
          - container_runtime in ['containerd', 'cri-o']
        fail_msg: "Invalid container runtime choice. Please choose either 'containerd' or 'cri-o'."

    - name: Install containerd if chosen
      include_role:
        name: containerd-package-manager
      when: container_runtime == "containerd"

    - name: Install cri-o if chosen
      include_role:
        name: cri-o
      when: container_runtime == "cri-o"


