---
- name: Install containerd
  block:
    - name: Install containerd on Ubuntu
      apt:
        name: containerd.io
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install containerd on CentOS
      yum:
        name: containerd.io
        state: present
      when: ansible_distribution == "CentOS"

    - name: Install containerd on Debian
      apt:
        name: containerd.io
        state: present
      when: ansible_distribution == "Debian"

    - name: Install containerd on Fedora
      dnf:
        name: containerd.io
        state: present
      when: ansible_distribution == "Fedora"

- name: Configure and restart containerd
  block:
    - name: Configure containerd
      command: containerd config default | tee /etc/containerd/config.toml

    - name: Restart containerd
      service:
        name: containerd
        state: restarted
        enabled: yes

